theme:                      "www.philipithomas.com"
title:                      "Philip I. Thomas"
baseURL:                    "https://www.philipithomas.com/"
description:                "Co-Founder and CEO of Staffjoy. Previously a Y Combinator Fellow, OpenDNS Senior Engineer, and WUSTL engineering and physics alumnus."
buildDrafts:                true
buildFuture:                true
relativeURLs:               true
canonifyURLs:               false
config:                     "config.yaml"
defaultExtension:           "md"
defaultLayout:              "post"
MetaDataFormat:             "yaml"
LanguageCode:               "en"

# Theme
Params:
    author: "Philip I. Thomas"
    TwitterUser: "philipithomas"
    CoverPhoto: "/cover.jpg"

permalinks:
    post: "/:filename/"
    page: "/:filename/"
